kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluid-installer
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - pods
      - pods/exec
      - nodes
      - events
      - namespaces
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - statefulsets
      - deployments
      - deployments/scale
      - deployments/status
      - daemonsets/status
      - statefulsets/status
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - jobs/status
      - cronjobs
      - cronjobs/status
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
    verbs: ["*"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - csidrivers
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups: ["data.fluid.io"]
    resources:
      - alluxioruntimes
      - jindoruntimes
      - goosefsruntimes
      - juicefsruntimes
      - thinruntimes
      - efcruntimes
      - vineyardruntimes
      - datasets
      - datamigrates
      - dataloads
      - databackups
      - dataprocesses
      - thinruntimeprofiles
      - alluxioruntimes/status
      - jindoruntimes/status
      - goosefsruntimes/status
      - juicefsruntimes/status
      - thinruntimes/status
      - efcruntimes/status
      - vineyardruntimes/status
      - datasets/status
      - datamigrates/status
      - dataloads/status
      - databackups/status
      - dataprocesses/status
      - thinruntimeprofiles/status
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - replicasets/status
    verbs: ["get", "list", "watch"]

---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - 'apps'
      - 'batch'
      - 'app.k8s.io'
      - 'autoscaling'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - 'networking.k8s.io'
    resources:
      - 'ingresses'
      - 'networkpolicies'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluid-ext-jsbundle-manager
rules:
- apiGroups:
  - "extensions.kubesphere.io"
  resources:
  - jsbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
