apiVersion: v2
appVersion: 1.0.5-7e917c7
description: A Helm chart to deploy fluid in Kubernetes
home: https://github.com/fluid-cloudnative/fluid
keywords:
- category:data
- fluid
- namespace:fluid-system
- releaseName:fluid
name: fluid
type: application
version: 1.0.5
